"use strict";
exports.MOCKNOUNS = [
    {
        id: 1,
        name: 'AppxPackage',
        items: ['aAppxPackage1 | mockAttr1 | mockAttr2 | mockAttr3',
            'aAppxPackage2 | mockAttr1 | mockAttr2 | mockAttr3',
            'bAppxPackage3 | mockAttr1 | mockAttr2 | mockAttr3',
            'bAppxPackage4 | mockAttr1 | mockAttr2 | mockAttr3',
            'cAppxPackage5 | mockAttr1 | mockAttr2 | mockAttr3',
            'cAppxPackage6 | mockAttr1 | mockAttr2 | mockAttr3',
            'dAppxPackage7 | mockAttr1 | mockAttr2 | mockAttr3',
            'dAppxPackage1 | mockAttr1 | mockAttr2 | mockAttr3',
            'eAppxPackage2 | mockAttr1 | mockAttr2 | mockAttr3',
            'eAppxPackage3 | mockAttr1 | mockAttr2 | mockAttr3',
            'fAppxPackage4 | mockAttr1 | mockAttr2 | mockAttr3',
            'fAppxPackage5 | mockAttr1 | mockAttr2 | mockAttr3',
            'gAppxPackage6 | mockAttr1 | mockAttr2 | mockAttr3',
            'gAppxPackage7 | mockAttr1 | mockAttr2 | mockAttr3']
    },
    {
        id: 2,
        name: 'BitlockerVolume',
        items: ['aBitlockerVolume | mockAttr1 | mockAttr2 | mockAttr3',
            'aBitlockerVolume2 | mockAttr1 | mockAttr2 | mockAttr3',
            'bBitlockerVolume3 | mockAttr1 | mockAttr2 | mockAttr3',
            'bBitlockerVolume4 | mockAttr1 | mockAttr2 | mockAttr3',
            'cBitlockerVolume5 | mockAttr1 | mockAttr2 | mockAttr3',
            'cBitlockerVolume6 | mockAttr1 | mockAttr2 | mockAttr3',
            'dBitlockerVolume7 | mockAttr1 | mockAttr2 | mockAttr3',
            'dBitlockerVolume | mockAttr1 | mockAttr2 | mockAttr3',
            'eBitlockerVolume2 | mockAttr1 | mockAttr2 | mockAttr3',
            'eBitlockerVolume3 | mockAttr1 | mockAttr2 | mockAttr3',
            'fBitlockerVolume4 | mockAttr1 | mockAttr2 | mockAttr3',
            'fBitlockerVolume5 | mockAttr1 | mockAttr2 | mockAttr3',
            'gBitlockerVolume6 | mockAttr1 | mockAttr2 | mockAttr3',
            'gBitlockerVolume7 | mockAttr1 | mockAttr2 | mockAttr3']
    },
    {
        id: 3,
        name: 'NetFirewallRules',
        items: ['aNetFirewallRules | mockAttr1 | mockAttr2 | mockAttr3',
            'aNetFirewallRules2 | mockAttr1 | mockAttr2 | mockAttr3',
            'bNetFirewallRules3 | mockAttr1 | mockAttr2 | mockAttr3',
            'bNetFirewallRules4 | mockAttr1 | mockAttr2 | mockAttr3',
            'cNetFirewallRules5 | mockAttr1 | mockAttr2 | mockAttr3',
            'cNetFirewallRules6 | mockAttr1 | mockAttr2 | mockAttr3',
            'dNetFirewallRules7 | mockAttr1 | mockAttr2 | mockAttr3',
            'dNetFirewallRules | mockAttr1 | mockAttr2 | mockAttr3',
            'eNetFirewallRules2 | mockAttr1 | mockAttr2 | mockAttr3',
            'eNetFirewallRules3 | mockAttr1 | mockAttr2 | mockAttr3',
            'fNetFirewallRules4 | mockAttr1 | mockAttr2 | mockAttr3',
            'fNetFirewallRules5 | mockAttr1 | mockAttr2 | mockAttr3',
            'gNetFirewallRules6 | mockAttr1 | mockAttr2 | mockAttr3',
            'gNetFirewallRules7 | mockAttr1 | mockAttr2 | mockAttr3']
    },
    {
        id: 4,
        name: 'PackageProvider',
        items: ['aPackageProvider | mockAttr1 | mockAttr2 | mockAttr3',
            'aPackageProvider2 | mockAttr1 | mockAttr2 | mockAttr3',
            'bPackageProvider3 | mockAttr1 | mockAttr2 | mockAttr3',
            'bPackageProvider4 | mockAttr1 | mockAttr2 | mockAttr3',
            'cPackageProvider5 | mockAttr1 | mockAttr2 | mockAttr3',
            'cPackageProvider6 | mockAttr1 | mockAttr2 | mockAttr3',
            'dPackageProvider7 | mockAttr1 | mockAttr2 | mockAttr3',
            'dPackageProvider | mockAttr1 | mockAttr2 | mockAttr3',
            'ePackageProvider2 | mockAttr1 | mockAttr2 | mockAttr3',
            'ePackageProvider3 | mockAttr1 | mockAttr2 | mockAttr3',
            'fPackageProvider4 | mockAttr1 | mockAttr2 | mockAttr3',
            'fPackageProvider5 | mockAttr1 | mockAttr2 | mockAttr3',
            'gPackageProvider6 | mockAttr1 | mockAttr2 | mockAttr3',
            'gPackageProvider7 | mockAttr1 | mockAttr2 | mockAttr3']
    },
    {
        id: 5,
        name: 'PhysicalDisk',
        items: ['aPhysicalDisk | mockAttr1 | mockAttr2 | mockAttr3',
            'aPhysicalDisk2 | mockAttr1 | mockAttr2 | mockAttr3',
            'bPhysicalDisk3 | mockAttr1 | mockAttr2 | mockAttr3',
            'bPhysicalDisk4 | mockAttr1 | mockAttr2 | mockAttr3',
            'cPhysicalDisk5 | mockAttr1 | mockAttr2 | mockAttr3',
            'cPhysicalDisk6 | mockAttr1 | mockAttr2 | mockAttr3',
            'dPhysicalDisk7 | mockAttr1 | mockAttr2 | mockAttr3',
            'dPhysicalDisk | mockAttr1 | mockAttr2 | mockAttr3',
            'ePhysicalDisk2 | mockAttr1 | mockAttr2 | mockAttr3',
            'ePhysicalDisk3 | mockAttr1 | mockAttr2 | mockAttr3',
            'fPhysicalDisk4 | mockAttr1 | mockAttr2 | mockAttr3',
            'fPhysicalDisk5 | mockAttr1 | mockAttr2 | mockAttr3',
            'gPhysicalDisk6 | mockAttr1 | mockAttr2 | mockAttr3',
            'gPhysicalDisk7 | mockAttr1 | mockAttr2 | mockAttr3']
    },
    {
        id: 6,
        name: 'Services',
        items: ['aServices | mockAttr1 | mockAttr2 | mockAttr3',
            'aServices2 | mockAttr1 | mockAttr2 | mockAttr3',
            'bServices3 | mockAttr1 | mockAttr2 | mockAttr3',
            'bServices4 | mockAttr1 | mockAttr2 | mockAttr3',
            'cServices5 | mockAttr1 | mockAttr2 | mockAttr3',
            'cServices6 | mockAttr1 | mockAttr2 | mockAttr3',
            'dServices7 | mockAttr1 | mockAttr2 | mockAttr3',
            'dServices | mockAttr1 | mockAttr2 | mockAttr3',
            'eServices2 | mockAttr1 | mockAttr2 | mockAttr3',
            'eServices3 | mockAttr1 | mockAttr2 | mockAttr3',
            'fServices4 | mockAttr1 | mockAttr2 | mockAttr3',
            'fServices5 | mockAttr1 | mockAttr2 | mockAttr3',
            'gServices6 | mockAttr1 | mockAttr2 | mockAttr3',
            'gServices7 | mockAttr1 | mockAttr2 | mockAttr3']
    },
    {
        id: 7,
        name: 'StorageFileServer',
        items: ['aStorageFileServer | mockAttr1 | mockAttr2 | mockAttr3',
            'aStorageFileServer2 | mockAttr1 | mockAttr2 | mockAttr3',
            'bStorageFileServer3 | mockAttr1 | mockAttr2 | mockAttr3',
            'bStorageFileServer4 | mockAttr1 | mockAttr2 | mockAttr3',
            'cStorageFileServer5 | mockAttr1 | mockAttr2 | mockAttr3',
            'cStorageFileServer6 | mockAttr1 | mockAttr2 | mockAttr3',
            'dStorageFileServer7 | mockAttr1 | mockAttr2 | mockAttr3',
            'dStorageFileServer | mockAttr1 | mockAttr2 | mockAttr3',
            'eStorageFileServer2 | mockAttr1 | mockAttr2 | mockAttr3',
            'eStorageFileServer3 | mockAttr1 | mockAttr2 | mockAttr3',
            'fStorageFileServer4 | mockAttr1 | mockAttr2 | mockAttr3',
            'fStorageFileServer5 | mockAttr1 | mockAttr2 | mockAttr3',
            'gStorageFileServer6 | mockAttr1 | mockAttr2 | mockAttr3',
            'gStorageFileServer7 | mockAttr1 | mockAttr2 | mockAttr3']
    },
    {
        id: 8,
        name: 'VMs',
        items: ['aVMs | mockAttr1 | mockAttr2 | mockAttr3',
            'aVMs2 | mockAttr1 | mockAttr2 | mockAttr3',
            'bVMs3 | mockAttr1 | mockAttr2 | mockAttr3',
            'bVMs4 | mockAttr1 | mockAttr2 | mockAttr3',
            'cVMs5 | mockAttr1 | mockAttr2 | mockAttr3',
            'cVMs6 | mockAttr1 | mockAttr2 | mockAttr3',
            'dVMs7 | mockAttr1 | mockAttr2 | mockAttr3',
            'dVMs | mockAttr1 | mockAttr2 | mockAttr3',
            'fVMs2 | mockAttr1 | mockAttr2 | mockAttr3',
            'fVMs3 | mockAttr1 | mockAttr2 | mockAttr3',
            'gVMs4 | mockAttr1 | mockAttr2 | mockAttr3',
            'gVMs5 | mockAttr1 | mockAttr2 | mockAttr3',
            'hVMs6 | mockAttr1 | mockAttr2 | mockAttr3',
            'hVMs7 | mockAttr1 | mockAttr2 | mockAttr3']
    },
    {
        id: 9,
        name: 'Volume',
        items: ['aVolume | mockAttr1 | mockAttr2 | mockAttr3',
            'aVolume2 | mockAttr1 | mockAttr2 | mockAttr3',
            'bVolume3 | mockAttr1 | mockAttr2 | mockAttr3',
            'bVolume4 | mockAttr1 | mockAttr2 | mockAttr3',
            'cVolume5 | mockAttr1 | mockAttr2 | mockAttr3',
            'cVolume6 | mockAttr1 | mockAttr2 | mockAttr3',
            'dVolume7 | mockAttr1 | mockAttr2 | mockAttr3',
            'dVolume | mockAttr1 | mockAttr2 | mockAttr3',
            'eVolume2 | mockAttr1 | mockAttr2 | mockAttr3',
            'eVolume3 | mockAttr1 | mockAttr2 | mockAttr3',
            'fVolume4 | mockAttr1 | mockAttr2 | mockAttr3',
            'fVolume5 | mockAttr1 | mockAttr2 | mockAttr3',
            'gVolume6 | mockAttr1 | mockAttr2 | mockAttr3',
            'gVolume7 | mockAttr1 | mockAttr2 | mockAttr3']
    },
    {
        id: 10,
        name: 'WmiEvent',
        items: ['aWmiEvent | mockAttr1 | mockAttr2 | mockAttr3',
            'aWmiEvent2 | mockAttr1 | mockAttr2 | mockAttr3',
            'bWmiEvent3 | mockAttr1 | mockAttr2 | mockAttr3',
            'bWmiEvent4 | mockAttr1 | mockAttr2 | mockAttr3',
            'cWmiEvent5 | mockAttr1 | mockAttr2 | mockAttr3',
            'cWmiEvent6 | mockAttr1 | mockAttr2 | mockAttr3',
            'dWmiEvent7 | mockAttr1 | mockAttr2 | mockAttr3',
            'dWmiEvent | mockAttr1 | mockAttr2 | mockAttr3',
            'eWmiEvent2 | mockAttr1 | mockAttr2 | mockAttr3',
            'eWmiEvent3 | mockAttr1 | mockAttr2 | mockAttr3',
            'fWmiEvent4 | mockAttr1 | mockAttr2 | mockAttr3',
            'fWmiEvent5 | mockAttr1 | mockAttr2 | mockAttr3',
            'gWmiEvent6 | mockAttr1 | mockAttr2 | mockAttr3',
            'gWmiEvent7 | mockAttr1 | mockAttr2 | mockAttr3']
    },
    {
        id: 11,
        name: 'AppxPackage',
        items: ['aAppxPackage1 | mockAttr1 | mockAttr2 | mockAttr3',
            'aAppxPackage2 | mockAttr1 | mockAttr2 | mockAttr3',
            'bAppxPackage3 | mockAttr1 | mockAttr2 | mockAttr3',
            'bAppxPackage4 | mockAttr1 | mockAttr2 | mockAttr3',
            'cAppxPackage5 | mockAttr1 | mockAttr2 | mockAttr3',
            'cAppxPackage6 | mockAttr1 | mockAttr2 | mockAttr3',
            'dAppxPackage7 | mockAttr1 | mockAttr2 | mockAttr3',
            'dAppxPackage1 | mockAttr1 | mockAttr2 | mockAttr3',
            'eAppxPackage2 | mockAttr1 | mockAttr2 | mockAttr3',
            'eAppxPackage3 | mockAttr1 | mockAttr2 | mockAttr3',
            'fAppxPackage4 | mockAttr1 | mockAttr2 | mockAttr3',
            'fAppxPackage5 | mockAttr1 | mockAttr2 | mockAttr3',
            'gAppxPackage6 | mockAttr1 | mockAttr2 | mockAttr3',
            'gAppxPackage7 | mockAttr1 | mockAttr2 | mockAttr3']
    },
    {
        id: 12,
        name: 'BitlockerVolume',
        items: ['aBitlockerVolume | mockAttr1 | mockAttr2 | mockAttr3',
            'aBitlockerVolume2 | mockAttr1 | mockAttr2 | mockAttr3',
            'bBitlockerVolume3 | mockAttr1 | mockAttr2 | mockAttr3',
            'bBitlockerVolume4 | mockAttr1 | mockAttr2 | mockAttr3',
            'cBitlockerVolume5 | mockAttr1 | mockAttr2 | mockAttr3',
            'cBitlockerVolume6 | mockAttr1 | mockAttr2 | mockAttr3',
            'dBitlockerVolume7 | mockAttr1 | mockAttr2 | mockAttr3',
            'dBitlockerVolume | mockAttr1 | mockAttr2 | mockAttr3',
            'eBitlockerVolume2 | mockAttr1 | mockAttr2 | mockAttr3',
            'eBitlockerVolume3 | mockAttr1 | mockAttr2 | mockAttr3',
            'fBitlockerVolume4 | mockAttr1 | mockAttr2 | mockAttr3',
            'fBitlockerVolume5 | mockAttr1 | mockAttr2 | mockAttr3',
            'gBitlockerVolume6 | mockAttr1 | mockAttr2 | mockAttr3',
            'gBitlockerVolume7 | mockAttr1 | mockAttr2 | mockAttr3']
    },
    {
        id: 13,
        name: 'NetFirewallRules',
        items: ['aNetFirewallRules | mockAttr1 | mockAttr2 | mockAttr3',
            'aNetFirewallRules2 | mockAttr1 | mockAttr2 | mockAttr3',
            'bNetFirewallRules3 | mockAttr1 | mockAttr2 | mockAttr3',
            'bNetFirewallRules4 | mockAttr1 | mockAttr2 | mockAttr3',
            'cNetFirewallRules5 | mockAttr1 | mockAttr2 | mockAttr3',
            'cNetFirewallRules6 | mockAttr1 | mockAttr2 | mockAttr3',
            'dNetFirewallRules7 | mockAttr1 | mockAttr2 | mockAttr3',
            'dNetFirewallRules | mockAttr1 | mockAttr2 | mockAttr3',
            'eNetFirewallRules2 | mockAttr1 | mockAttr2 | mockAttr3',
            'eNetFirewallRules3 | mockAttr1 | mockAttr2 | mockAttr3',
            'fNetFirewallRules4 | mockAttr1 | mockAttr2 | mockAttr3',
            'fNetFirewallRules5 | mockAttr1 | mockAttr2 | mockAttr3',
            'gNetFirewallRules6 | mockAttr1 | mockAttr2 | mockAttr3',
            'gNetFirewallRules7 | mockAttr1 | mockAttr2 | mockAttr3']
    },
    {
        id: 14,
        name: 'PackageProvider',
        items: ['aPackageProvider | mockAttr1 | mockAttr2 | mockAttr3',
            'aPackageProvider2 | mockAttr1 | mockAttr2 | mockAttr3',
            'bPackageProvider3 | mockAttr1 | mockAttr2 | mockAttr3',
            'bPackageProvider4 | mockAttr1 | mockAttr2 | mockAttr3',
            'cPackageProvider5 | mockAttr1 | mockAttr2 | mockAttr3',
            'cPackageProvider6 | mockAttr1 | mockAttr2 | mockAttr3',
            'dPackageProvider7 | mockAttr1 | mockAttr2 | mockAttr3',
            'dPackageProvider | mockAttr1 | mockAttr2 | mockAttr3',
            'ePackageProvider2 | mockAttr1 | mockAttr2 | mockAttr3',
            'ePackageProvider3 | mockAttr1 | mockAttr2 | mockAttr3',
            'fPackageProvider4 | mockAttr1 | mockAttr2 | mockAttr3',
            'fPackageProvider5 | mockAttr1 | mockAttr2 | mockAttr3',
            'gPackageProvider6 | mockAttr1 | mockAttr2 | mockAttr3',
            'gPackageProvider7 | mockAttr1 | mockAttr2 | mockAttr3']
    },
    {
        id: 15,
        name: 'PhysicalDisk',
        items: ['aPhysicalDisk | mockAttr1 | mockAttr2 | mockAttr3',
            'aPhysicalDisk2 | mockAttr1 | mockAttr2 | mockAttr3',
            'bPhysicalDisk3 | mockAttr1 | mockAttr2 | mockAttr3',
            'bPhysicalDisk4 | mockAttr1 | mockAttr2 | mockAttr3',
            'cPhysicalDisk5 | mockAttr1 | mockAttr2 | mockAttr3',
            'cPhysicalDisk6 | mockAttr1 | mockAttr2 | mockAttr3',
            'dPhysicalDisk7 | mockAttr1 | mockAttr2 | mockAttr3',
            'dPhysicalDisk | mockAttr1 | mockAttr2 | mockAttr3',
            'ePhysicalDisk2 | mockAttr1 | mockAttr2 | mockAttr3',
            'ePhysicalDisk3 | mockAttr1 | mockAttr2 | mockAttr3',
            'fPhysicalDisk4 | mockAttr1 | mockAttr2 | mockAttr3',
            'fPhysicalDisk5 | mockAttr1 | mockAttr2 | mockAttr3',
            'gPhysicalDisk6 | mockAttr1 | mockAttr2 | mockAttr3',
            'gPhysicalDisk7 | mockAttr1 | mockAttr2 | mockAttr3']
    },
    {
        id: 16,
        name: 'Services',
        items: ['aServices | mockAttr1 | mockAttr2 | mockAttr3',
            'aServices2 | mockAttr1 | mockAttr2 | mockAttr3',
            'bServices3 | mockAttr1 | mockAttr2 | mockAttr3',
            'bServices4 | mockAttr1 | mockAttr2 | mockAttr3',
            'cServices5 | mockAttr1 | mockAttr2 | mockAttr3',
            'cServices6 | mockAttr1 | mockAttr2 | mockAttr3',
            'dServices7 | mockAttr1 | mockAttr2 | mockAttr3',
            'dServices | mockAttr1 | mockAttr2 | mockAttr3',
            'eServices2 | mockAttr1 | mockAttr2 | mockAttr3',
            'eServices3 | mockAttr1 | mockAttr2 | mockAttr3',
            'fServices4 | mockAttr1 | mockAttr2 | mockAttr3',
            'fServices5 | mockAttr1 | mockAttr2 | mockAttr3',
            'gServices6 | mockAttr1 | mockAttr2 | mockAttr3',
            'gServices7 | mockAttr1 | mockAttr2 | mockAttr3']
    },
    {
        id: 17,
        name: 'StorageFileServer',
        items: ['aStorageFileServer | mockAttr1 | mockAttr2 | mockAttr3',
            'aStorageFileServer2 | mockAttr1 | mockAttr2 | mockAttr3',
            'bStorageFileServer3 | mockAttr1 | mockAttr2 | mockAttr3',
            'bStorageFileServer4 | mockAttr1 | mockAttr2 | mockAttr3',
            'cStorageFileServer5 | mockAttr1 | mockAttr2 | mockAttr3',
            'cStorageFileServer6 | mockAttr1 | mockAttr2 | mockAttr3',
            'dStorageFileServer7 | mockAttr1 | mockAttr2 | mockAttr3',
            'dStorageFileServer | mockAttr1 | mockAttr2 | mockAttr3',
            'eStorageFileServer2 | mockAttr1 | mockAttr2 | mockAttr3',
            'eStorageFileServer3 | mockAttr1 | mockAttr2 | mockAttr3',
            'fStorageFileServer4 | mockAttr1 | mockAttr2 | mockAttr3',
            'fStorageFileServer5 | mockAttr1 | mockAttr2 | mockAttr3',
            'gStorageFileServer6 | mockAttr1 | mockAttr2 | mockAttr3',
            'gStorageFileServer7 | mockAttr1 | mockAttr2 | mockAttr3']
    },
    {
        id: 18,
        name: 'VMs',
        items: ['aVMs | mockAttr1 | mockAttr2 | mockAttr3',
            'aVMs2 | mockAttr1 | mockAttr2 | mockAttr3',
            'bVMs3 | mockAttr1 | mockAttr2 | mockAttr3',
            'bVMs4 | mockAttr1 | mockAttr2 | mockAttr3',
            'cVMs5 | mockAttr1 | mockAttr2 | mockAttr3',
            'cVMs6 | mockAttr1 | mockAttr2 | mockAttr3',
            'dVMs7 | mockAttr1 | mockAttr2 | mockAttr3',
            'dVMs | mockAttr1 | mockAttr2 | mockAttr3',
            'fVMs2 | mockAttr1 | mockAttr2 | mockAttr3',
            'fVMs3 | mockAttr1 | mockAttr2 | mockAttr3',
            'gVMs4 | mockAttr1 | mockAttr2 | mockAttr3',
            'gVMs5 | mockAttr1 | mockAttr2 | mockAttr3',
            'hVMs6 | mockAttr1 | mockAttr2 | mockAttr3',
            'hVMs7 | mockAttr1 | mockAttr2 | mockAttr3']
    },
    {
        id: 19,
        name: 'Volume',
        items: ['aVolume | mockAttr1 | mockAttr2 | mockAttr3',
            'aVolume2 | mockAttr1 | mockAttr2 | mockAttr3',
            'bVolume3 | mockAttr1 | mockAttr2 | mockAttr3',
            'bVolume4 | mockAttr1 | mockAttr2 | mockAttr3',
            'cVolume5 | mockAttr1 | mockAttr2 | mockAttr3',
            'cVolume6 | mockAttr1 | mockAttr2 | mockAttr3',
            'dVolume7 | mockAttr1 | mockAttr2 | mockAttr3',
            'dVolume | mockAttr1 | mockAttr2 | mockAttr3',
            'eVolume2 | mockAttr1 | mockAttr2 | mockAttr3',
            'eVolume3 | mockAttr1 | mockAttr2 | mockAttr3',
            'fVolume4 | mockAttr1 | mockAttr2 | mockAttr3',
            'fVolume5 | mockAttr1 | mockAttr2 | mockAttr3',
            'gVolume6 | mockAttr1 | mockAttr2 | mockAttr3',
            'gVolume7 | mockAttr1 | mockAttr2 | mockAttr3']
    },
    {
        id: 20,
        name: 'WmiEvent',
        items: ['aWmiEvent | mockAttr1 | mockAttr2 | mockAttr3',
            'aWmiEvent2 | mockAttr1 | mockAttr2 | mockAttr3',
            'bWmiEvent3 | mockAttr1 | mockAttr2 | mockAttr3',
            'bWmiEvent4 | mockAttr1 | mockAttr2 | mockAttr3',
            'cWmiEvent5 | mockAttr1 | mockAttr2 | mockAttr3',
            'cWmiEvent6 | mockAttr1 | mockAttr2 | mockAttr3',
            'dWmiEvent7 | mockAttr1 | mockAttr2 | mockAttr3',
            'dWmiEvent | mockAttr1 | mockAttr2 | mockAttr3',
            'eWmiEvent2 | mockAttr1 | mockAttr2 | mockAttr3',
            'eWmiEvent3 | mockAttr1 | mockAttr2 | mockAttr3',
            'fWmiEvent4 | mockAttr1 | mockAttr2 | mockAttr3',
            'fWmiEvent5 | mockAttr1 | mockAttr2 | mockAttr3',
            'gWmiEvent6 | mockAttr1 | mockAttr2 | mockAttr3',
            'gWmiEvent7 | mockAttr1 | mockAttr2 | mockAttr3']
    }
];
//# sourceMappingURL=mock-nouns.js.map